# Use root/example as user/password credentials
version: '3.1'

services:
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: majom2
            MYSQL_USER: sdeli
            MYSQL_PASSWORD: dalias19
        networks:
          - ausztriarecruitment
        volumes:
          - /home/sandor/db:/src

    ausztriaiallas:
       image: sdeli/ausztriaiallas:1.0
       networks:
          - ausztriarecruitment
       stdin_open: true
       tty: true
       ports:
         - 4000:4000
       volumes:
         - /home/sandor/startup-scripts/austria-recruitment-app/:/austria-recruitment/app
networks:
    ausztriarecruitment:
        driver: bridge